In [1048]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [1049]:
# Classes correspond to:
# 0: Red Manatee
# 1: Green Manatee
# 2: Black Board
# 3: White Board
# 4: Blue Dock Pond

# Import data from csv file into numpy array
data = np.genfromtxt('/home/mdelab/ieee-robotics-2023-code/src/jetson_code/color_classification/rgb_data.csv', delimiter=',', skip_header=1)

# Split data into features and labels
X = data[:, 0:3]
y = data[:, 3]

print(X)

# Divide all features by 800 to normalize
X = X / 800

print(X)

# Generate training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Print shapes of training and testing data
print(X_train.shape)
print(X_test.shape)



[[400. 143. 133.]
 [409. 145. 135.]
 [412. 146. 136.]
 [276. 230. 156.]
 [281. 239. 164.]
 [291. 262. 178.]
 [251. 119. 105.]
 [251. 119. 104.]
 [250. 118. 104.]
 [848. 845. 735.]
 [820. 821. 719.]
 [846. 856. 750.]
 [268. 199. 250.]
 [270. 203. 255.]
 [267. 198. 250.]]
[[0.5     0.17875 0.16625]
 [0.51125 0.18125 0.16875]
 [0.515   0.1825  0.17   ]
 [0.345   0.2875  0.195  ]
 [0.35125 0.29875 0.205  ]
 [0.36375 0.3275  0.2225 ]
 [0.31375 0.14875 0.13125]
 [0.31375 0.14875 0.13   ]
 [0.3125  0.1475  0.13   ]
 [1.06    1.05625 0.91875]
 [1.025   1.02625 0.89875]
 [1.0575  1.07    0.9375 ]
 [0.335   0.24875 0.3125 ]
 [0.3375  0.25375 0.31875]
 [0.33375 0.2475  0.3125 ]]
(12, 3)
(3, 3)


In [1050]:
# Create SVM classifier
clf = SVC(kernel='poly', C=10, gamma=0.001)
clf.fit(X, y)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [1051]:
# Evaluate classifier on test set
print("Accuracy: ", clf.score(X_test, y_test))

# Print the actual class vs the predicted class
print("Actual: ", y_test)
print("Predicted: ", clf.predict(X_test))

# Print the unnormailzed RGB values of the test set
print("RGB Values: ", X_test * 800)

Accuracy:  1.0
Actual:  [2. 1. 3.]
Predicted:  [2. 1. 3.]
RGB Values:  [[251. 119. 105.]
 [291. 262. 178.]
 [846. 856. 750.]]
